# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1114, 594)
        self.poleZapisu = QtWidgets.QListWidget(parent=Dialog)
        self.poleZapisu.setGeometry(QtCore.QRect(160, 330, 256, 192))
        self.poleZapisu.setObjectName("poleZapisu")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(120, 40, 731, 231))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.imieEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.imieEdit.setObjectName("imieEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.imieEdit)
        self.nazwiskoEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.nazwiskoEdit.setObjectName("nazwiskoEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nazwiskoEdit)
        self.telEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.telEdit.setObjectName("telEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.telEdit)
        self.peselEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.peselEdit.setObjectName("peselEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.peselEdit)
        self.zapiszButton = QtWidgets.QPushButton(parent=self.widget)
        self.zapiszButton.setObjectName("zapiszButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.zapiszButton)
        self.zapiszPlikButton = QtWidgets.QPushButton(parent=self.widget)
        self.zapiszPlikButton.setObjectName("zapiszPlikButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.zapiszPlikButton)
        self.umowaCheckbox = QtWidgets.QCheckBox(parent=self.widget)
        self.umowaCheckbox.setObjectName("umowaCheckbox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.umowaCheckbox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Imie"))
        self.label_2.setText(_translate("Dialog", "Nazwisko"))
        self.label_3.setText(_translate("Dialog", "numer Tel"))
        self.label_4.setText(_translate("Dialog", "PESEL"))
        self.zapiszButton.setText(_translate("Dialog", "Zapisz"))
        self.zapiszPlikButton.setText(_translate("Dialog", "Zapisz do pliku (wip)"))
        self.umowaCheckbox.setText(_translate("Dialog", "Umowa o prace"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
